---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infra:
    - Unifi:
        href: https://unifi.ui.com/consoles/A89C6C8605C80000000009857DB9000000000A0AFF0D0000000068EABFB4:88181522/network/default/dashboard
        description: Unifi Controller
        
    - Proxmox:
        href: https://proxmox.skyelowry.home:8006
        description: Proxmox Server

    - TrueNAS:
        href: https://truenas.skyelowry.home
        description: TrueNAS
